# npx create-react-app envy

# yarn

# yarn add node-sass

# yarn add react-router-dom

# yarn add firebase

# yarn add redux redux-logger react-redux

# yarn add reselect

# yarn add redux-persist

# yarn add react-stripe-checkout

# yarn add styled-components